regions = [
    ["mask" => "+247-####", "cc" => "AC", "name" => "Ascension", "desc" => "", "name_ru" => "Остров Вознесения", "desc_ru" => ""],
    ["mask" => "+376-###-###", "cc" => "AD", "name" => "Andorra", "desc" => "", "name_ru" => "Андорра", "desc_ru" => ""],
    ["mask" => "+971-5#-###-####", "cc" => "AE", "name" => "United Arab Emirates", "desc" => "mobile", "name_ru" => "Объединенные Арабские Эмираты", "desc_ru" => "мобильные"],
    ["mask" => "+971-#-###-####", "cc" => "AE", "name" => "United Arab Emirates", "desc" => "", "name_ru" => "Объединенные Арабские Эмираты", "desc_ru" => ""],
    ["mask" => "+93-##-###-####", "cc" => "AF", "name" => "Afghanistan", "desc" => "", "name_ru" => "Афганистан", "desc_ru" => ""],
    ["mask" => "+1(268)###-####", "cc" => "AG", "name" => "Antigua & Barbuda", "desc" => "", "name_ru" => "Антигуа и Барбуда", "desc_ru" => ""],
    ["mask" => "+1(264)###-####", "cc" => "AI", "name" => "Anguilla", "desc" => "", "name_ru" => "Ангилья", "desc_ru" => ""],
    ["mask" => "+355(###)###-###", "cc" => "AL", "name" => "Albania", "desc" => "", "name_ru" => "Албания", "desc_ru" => ""],
    ["mask" => "+374-##-###-###", "cc" => "AM", "name" => "Armenia", "desc" => "", "name_ru" => "Армения", "desc_ru" => ""],
    ["mask" => "+599-###-####", "cc" => "AN", "name" => "Caribbean Netherlands", "desc" => "", "name_ru" => "Карибские Нидерланды", "desc_ru" => ""],
    ["mask" => "+599-###-####", "cc" => "AN", "name" => "Netherlands Antilles", "desc" => "", "name_ru" => "Нидерландские Антильские острова", "desc_ru" => ""],
    ["mask" => "+599-9###-####", "cc" => "AN", "name" => "Netherlands Antilles", "desc" => "Curacao", "name_ru" => "Нидерландские Антильские острова", "desc_ru" => "Кюрасао"],
    ["mask" => "+244(###)###-###", "cc" => "AO", "name" => "Angola", "desc" => "", "name_ru" => "Ангола", "desc_ru" => ""],
    ["mask" => "+672-1##-###", "cc" => "AQ", "name" => "Australian bases in Antarctica", "desc" => "", "name_ru" => "Австралийская антарктическая база", "desc_ru" => ""],
    ["mask" => "+54(###)###-####", "cc" => "AR", "name" => "Argentina", "desc" => "", "name_ru" => "Аргентина", "desc_ru" => ""],
    ["mask" => "+1(684)###-####", "cc" => "AS", "name" => "American Samoa", "desc" => "", "name_ru" => "Американское Самоа", "desc_ru" => ""],
    ["mask" => "+43(###)###-####", "cc" => "AT", "name" => "Austria", "desc" => "", "name_ru" => "Австрия", "desc_ru" => ""],
    ["mask" => "+61-#-####-####", "cc" => "AU", "name" => "Australia", "desc" => "", "name_ru" => "Австралия", "desc_ru" => ""],
    ["mask" => "+297-###-####", "cc" => "AW", "name" => "Aruba", "desc" => "", "name_ru" => "Аруба", "desc_ru" => ""],
    ["mask" => "+994-##-###-##-##", "cc" => "AZ", "name" => "Azerbaijan", "desc" => "", "name_ru" => "Азербайджан", "desc_ru" => ""],
    ["mask" => "+387-##-#####", "cc" => "BA", "name" => "Bosnia and Herzegovina", "desc" => "", "name_ru" => "Босния и Герцеговина", "desc_ru" => ""],
    ["mask" => "+387-##-####", "cc" => "BA", "name" => "Bosnia and Herzegovina", "desc" => "", "name_ru" => "Босния и Герцеговина", "desc_ru" => ""],
    ["mask" => "+1(246)###-####", "cc" => "BB", "name" => "Barbados", "desc" => "", "name_ru" => "Барбадос", "desc_ru" => ""],
    ["mask" => "+880-##-###-###", "cc" => "BD", "name" => "Bangladesh", "desc" => "", "name_ru" => "Бангладеш", "desc_ru" => ""],
    ["mask" => "+32(###)###-###", "cc" => "BE", "name" => "Belgium", "desc" => "", "name_ru" => "Бельгия", "desc_ru" => ""],
    ["mask" => "+226-##-##-####", "cc" => "BF", "name" => "Burkina Faso", "desc" => "", "name_ru" => "Буркина Фасо", "desc_ru" => ""],
    ["mask" => "+359(###)###-###", "cc" => "BG", "name" => "Bulgaria", "desc" => "", "name_ru" => "Болгария", "desc_ru" => ""],
    ["mask" => "+973-####-####", "cc" => "BH", "name" => "Bahrain", "desc" => "", "name_ru" => "Бахрейн", "desc_ru" => ""],
    ["mask" => "+257-##-##-####", "cc" => "BI", "name" => "Burundi", "desc" => "", "name_ru" => "Бурунди", "desc_ru" => ""],
    ["mask" => "+229-##-##-####", "cc" => "BJ", "name" => "Benin", "desc" => "", "name_ru" => "Бенин", "desc_ru" => ""],
    ["mask" => "+1(441)###-####", "cc" => "BM", "name" => "Bermuda", "desc" => "", "name_ru" => "Бермудские острова", "desc_ru" => ""],
    ["mask" => "+673-###-####", "cc" => "BN", "name" => "Brunei Darussalam", "desc" => "", "name_ru" => "Бруней-Даруссалам", "desc_ru" => ""],
    ["mask" => "+591-#-###-####", "cc" => "BO", "name" => "Bolivia", "desc" => "", "name_ru" => "Боливия", "desc_ru" => ""],
    ["mask" => "+55(##)####-####", "cc" => "BR", "name" => "Brazil", "desc" => "", "name_ru" => "Бразилия", "desc_ru" => ""],
    ["mask" => "+55(##)7###-####", "cc" => "BR", "name" => "Brazil", "desc" => "mobile", "name_ru" => "Бразилия", "desc_ru" => "мобильные"],
    ["mask" => "+55(##)9####-####", "cc" => "BR", "name" => "Brazil", "desc" => "mobile", "name_ru" => "Бразилия", "desc_ru" => "мобильные"],
    ["mask" => "+1(242)###-####", "cc" => "BS", "name" => "Bahamas", "desc" => "", "name_ru" => "Багамские Острова", "desc_ru" => ""],
    ["mask" => "+975-17-###-###", "cc" => "BT", "name" => "Bhutan", "desc" => "", "name_ru" => "Бутан", "desc_ru" => ""],
    ["mask" => "+975-#-###-###", "cc" => "BT", "name" => "Bhutan", "desc" => "", "name_ru" => "Бутан", "desc_ru" => ""],
    ["mask" => "+267-##-###-###", "cc" => "BW", "name" => "Botswana", "desc" => "", "name_ru" => "Ботсвана", "desc_ru" => ""],
    ["mask" => "+375(##)###-##-##", "cc" => "BY", "name" => "Belarus", "desc" => "", "name_ru" => "Беларусь (Белоруссия)", "desc_ru" => ""],
    ["mask" => "+501-###-####", "cc" => "BZ", "name" => "Belize", "desc" => "", "name_ru" => "Белиз", "desc_ru" => ""],
    ["mask" => "+243(###)###-###", "cc" => "CD", "name" => "Dem. Rep. Congo", "desc" => "", "name_ru" => "Дем. Респ. Конго (Киншаса)", "desc_ru" => ""],
    ["mask" => "+236-##-##-####", "cc" => "CF", "name" => "Central African Republic", "desc" => "", "name_ru" => "Центральноафриканская Республика", "desc_ru" => ""],
    ["mask" => "+242-##-###-####", "cc" => "CG", "name" => "Congo (Brazzaville)", "desc" => "", "name_ru" => "Конго (Браззавиль)", "desc_ru" => ""],
    ["mask" => "+41-##-###-####", "cc" => "CH", "name" => "Switzerland", "desc" => "", "name_ru" => "Швейцария", "desc_ru" => ""],
    ["mask" => "+225-##-###-###", "cc" => "CI", "name" => "Cote d’Ivoire (Ivory Coast)", "desc" => "", "name_ru" => "Кот-д’Ивуар", "desc_ru" => ""],
    ["mask" => "+682-##-###", "cc" => "CK", "name" => "Cook Islands", "desc" => "", "name_ru" => "Острова Кука", "desc_ru" => ""],
    ["mask" => "+56-#-####-####", "cc" => "CL", "name" => "Chile", "desc" => "", "name_ru" => "Чили", "desc_ru" => ""],
    ["mask" => "+237-####-####", "cc" => "CM", "name" => "Cameroon", "desc" => "", "name_ru" => "Камерун", "desc_ru" => ""],
    ["mask" => "+86(###)####-####", "cc" => "CN", "name" => "China (PRC)", "desc" => "", "name_ru" => "Китайская Н.Р.", "desc_ru" => ""],
    ["mask" => "+86(###)####-###", "cc" => "CN", "name" => "China (PRC)", "desc" => "", "name_ru" => "Китайская Н.Р.", "desc_ru" => ""],
    ["mask" => "+86-##-#####-#####", "cc" => "CN", "name" => "China (PRC)", "desc" => "", "name_ru" => "Китайская Н.Р.", "desc_ru" => ""],
    ["mask" => "+57(###)###-####", "cc" => "CO", "name" => "Colombia", "desc" => "", "name_ru" => "Колумбия", "desc_ru" => ""],
    ["mask" => "+506-####-####", "cc" => "CR", "name" => "Costa Rica", "desc" => "", "name_ru" => "Коста-Рика", "desc_ru" => ""],
    ["mask" => "+53-#-###-####", "cc" => "CU", "name" => "Cuba", "desc" => "", "name_ru" => "Куба", "desc_ru" => ""],
    ["mask" => "+238(###)##-##", "cc" => "CV", "name" => "Cape Verde", "desc" => "", "name_ru" => "Кабо-Верде", "desc_ru" => ""],
    ["mask" => "+599-###-####", "cc" => "CW", "name" => "Curacao", "desc" => "", "name_ru" => "Кюрасао", "desc_ru" => ""],
    ["mask" => "+357-##-###-###", "cc" => "CY", "name" => "Cyprus", "desc" => "", "name_ru" => "Кипр", "desc_ru" => ""],
    ["mask" => "+420(###)###-###", "cc" => "CZ", "name" => "Czech Republic", "desc" => "", "name_ru" => "Чехия", "desc_ru" => ""],
    ["mask" => "+49(####)###-####", "cc" => "DE", "name" => "Germany", "desc" => "", "name_ru" => "Германия", "desc_ru" => ""],
    ["mask" => "+49(###)###-####", "cc" => "DE", "name" => "Germany", "desc" => "", "name_ru" => "Германия", "desc_ru" => ""],
    ["mask" => "+49(###)##-####", "cc" => "DE", "name" => "Germany", "desc" => "", "name_ru" => "Германия", "desc_ru" => ""],
    ["mask" => "+49(###)##-###", "cc" => "DE", "name" => "Germany", "desc" => "", "name_ru" => "Германия", "desc_ru" => ""],
    ["mask" => "+49(###)##-##", "cc" => "DE", "name" => "Germany", "desc" => "", "name_ru" => "Германия", "desc_ru" => ""],
    ["mask" => "+49-###-###", "cc" => "DE", "name" => "Germany", "desc" => "", "name_ru" => "Германия", "desc_ru" => ""],
    ["mask" => "+253-##-##-##-##", "cc" => "DJ", "name" => "Djibouti", "desc" => "", "name_ru" => "Джибути", "desc_ru" => ""],
    ["mask" => "+45-##-##-##-##", "cc" => "DK", "name" => "Denmark", "desc" => "", "name_ru" => "Дания", "desc_ru" => ""],
    ["mask" => "+1(767)###-####", "cc" => "DM", "name" => "Dominica", "desc" => "", "name_ru" => "Доминика", "desc_ru" => ""],
    ["mask" => "+1(809)###-####", "cc" => "DO", "name" => "Dominican Republic", "desc" => "", "name_ru" => "Доминиканская Республика", "desc_ru" => ""],
    ["mask" => "+1(829)###-####", "cc" => "DO", "name" => "Dominican Republic", "desc" => "", "name_ru" => "Доминиканская Республика", "desc_ru" => ""],
    ["mask" => "+1(849)###-####", "cc" => "DO", "name" => "Dominican Republic", "desc" => "", "name_ru" => "Доминиканская Республика", "desc_ru" => ""],
    ["mask" => "+213-##-###-####", "cc" => "DZ", "name" => "Algeria", "desc" => "", "name_ru" => "Алжир", "desc_ru" => ""],
    ["mask" => "+593-##-###-####", "cc" => "EC", "name" => "Ecuador ", "desc" => "mobile", "name_ru" => "Эквадор ", "desc_ru" => "мобильные"],
    ["mask" => "+593-#-###-####", "cc" => "EC", "name" => "Ecuador", "desc" => "", "name_ru" => "Эквадор", "desc_ru" => ""],
    ["mask" => "+372-####-####", "cc" => "EE", "name" => "Estonia ", "desc" => "mobile", "name_ru" => "Эстония ", "desc_ru" => "мобильные"],
    ["mask" => "+372-###-####", "cc" => "EE", "name" => "Estonia", "desc" => "", "name_ru" => "Эстония", "desc_ru" => ""],
    ["mask" => "+20(###)###-####", "cc" => "EG", "name" => "Egypt", "desc" => "", "name_ru" => "Египет", "desc_ru" => ""],
    ["mask" => "+291-#-###-###", "cc" => "ER", "name" => "Eritrea", "desc" => "", "name_ru" => "Эритрея", "desc_ru" => ""],
    ["mask" => "+34(###)###-###", "cc" => "ES", "name" => "Spain", "desc" => "", "name_ru" => "Испания", "desc_ru" => ""],
    ["mask" => "+251-##-###-####", "cc" => "ET", "name" => "Ethiopia", "desc" => "", "name_ru" => "Эфиопия", "desc_ru" => ""],
    ["mask" => "+358(###)###-##-##", "cc" => "FI", "name" => "Finland", "desc" => "", "name_ru" => "Финляндия", "desc_ru" => ""],
    ["mask" => "+679-##-#####", "cc" => "FJ", "name" => "Fiji", "desc" => "", "name_ru" => "Фиджи", "desc_ru" => ""],
    ["mask" => "+500-#####", "cc" => "FK", "name" => "Falkland Islands", "desc" => "", "name_ru" => "Фолклендские острова", "desc_ru" => ""],
    ["mask" => "+691-###-####", "cc" => "FM", "name" => "F.S. Micronesia", "desc" => "", "name_ru" => "Ф.Ш. Микронезии", "desc_ru" => ""],
    ["mask" => "+298-###-###", "cc" => "FO", "name" => "Faroe Islands", "desc" => "", "name_ru" => "Фарерские острова", "desc_ru" => ""],
    ["mask" => "+262-#####-####", "cc" => "FR", "name" => "Mayotte", "desc" => "", "name_ru" => "Майотта", "desc_ru" => ""],
    ["mask" => "+33(###)###-###", "cc" => "FR", "name" => "France", "desc" => "", "name_ru" => "Франция", "desc_ru" => ""],
    ["mask" => "+508-##-####", "cc" => "FR", "name" => "St Pierre & Miquelon", "desc" => "", "name_ru" => "Сен-Пьер и Микелон", "desc_ru" => ""],
    ["mask" => "+590(###)###-###", "cc" => "FR", "name" => "Guadeloupe", "desc" => "", "name_ru" => "Гваделупа", "desc_ru" => ""],
    ["mask" => "+241-#-##-##-##", "cc" => "GA", "name" => "Gabon", "desc" => "", "name_ru" => "Габон", "desc_ru" => ""],
    ["mask" => "+1(473)###-####", "cc" => "GD", "name" => "Grenada", "desc" => "", "name_ru" => "Гренада", "desc_ru" => ""],
    ["mask" => "+995(###)###-###", "cc" => "GE", "name" => "Rep. of Georgia", "desc" => "", "name_ru" => "Грузия", "desc_ru" => ""],
    ["mask" => "+594-#####-####", "cc" => "GF", "name" => "Guiana (French)", "desc" => "", "name_ru" => "Фр. Гвиана", "desc_ru" => ""],
    ["mask" => "+233(###)###-###", "cc" => "GH", "name" => "Ghana", "desc" => "", "name_ru" => "Гана", "desc_ru" => ""],
    ["mask" => "+350-###-#####", "cc" => "GI", "name" => "Gibraltar", "desc" => "", "name_ru" => "Гибралтар", "desc_ru" => ""],
    ["mask" => "+299-##-##-##", "cc" => "GL", "name" => "Greenland", "desc" => "", "name_ru" => "Гренландия", "desc_ru" => ""],
    ["mask" => "+220(###)##-##", "cc" => "GM", "name" => "Gambia", "desc" => "", "name_ru" => "Гамбия", "desc_ru" => ""],
    ["mask" => "+224-##-###-###", "cc" => "GN", "name" => "Guinea", "desc" => "", "name_ru" => "Гвинея", "desc_ru" => ""],
    ["mask" => "+240-##-###-####", "cc" => "GQ", "name" => "Equatorial Guinea", "desc" => "", "name_ru" => "Экваториальная Гвинея", "desc_ru" => ""],
    ["mask" => "+30(###)###-####", "cc" => "GR", "name" => "Greece", "desc" => "", "name_ru" => "Греция", "desc_ru" => ""],
    ["mask" => "+502-#-###-####", "cc" => "GT", "name" => "Guatemala", "desc" => "", "name_ru" => "Гватемала", "desc_ru" => ""],
    ["mask" => "+1(671)###-####", "cc" => "GU", "name" => "Guam", "desc" => "", "name_ru" => "Гуам", "desc_ru" => ""],
    ["mask" => "+245-#-######", "cc" => "GW", "name" => "Guinea-Bissau", "desc" => "", "name_ru" => "Гвинея-Бисау", "desc_ru" => ""],
    ["mask" => "+592-###-####", "cc" => "GY", "name" => "Guyana", "desc" => "", "name_ru" => "Гайана", "desc_ru" => ""],
    ["mask" => "+852-####-####", "cc" => "HK", "name" => "Hong Kong", "desc" => "", "name_ru" => "Гонконг", "desc_ru" => ""],
    ["mask" => "+504-####-####", "cc" => "HN", "name" => "Honduras", "desc" => "", "name_ru" => "Гондурас", "desc_ru" => ""],
    ["mask" => "+385-##-###-###", "cc" => "HR", "name" => "Croatia", "desc" => "", "name_ru" => "Хорватия", "desc_ru" => ""],
    ["mask" => "+509-##-##-####", "cc" => "HT", "name" => "Haiti", "desc" => "", "name_ru" => "Гаити", "desc_ru" => ""],
    ["mask" => "+36(###)###-###", "cc" => "HU", "name" => "Hungary", "desc" => "", "name_ru" => "Венгрия", "desc_ru" => ""],
    ["mask" => "+62(8##)###-####", "cc" => "ID", "name" => "Indonesia ", "desc" => "mobile", "name_ru" => "Индонезия ", "desc_ru" => "мобильные"],
    ["mask" => "+62-##-###-##", "cc" => "ID", "name" => "Indonesia", "desc" => "", "name_ru" => "Индонезия", "desc_ru" => ""],
    ["mask" => "+62-##-###-###", "cc" => "ID", "name" => "Indonesia", "desc" => "", "name_ru" => "Индонезия", "desc_ru" => ""],
    ["mask" => "+62-##-###-####", "cc" => "ID", "name" => "Indonesia", "desc" => "", "name_ru" => "Индонезия", "desc_ru" => ""],
    ["mask" => "+62(8##)###-###", "cc" => "ID", "name" => "Indonesia ", "desc" => "mobile", "name_ru" => "Индонезия ", "desc_ru" => "мобильные"],
    ["mask" => "+62(8##)###-##-###", "cc" => "ID", "name" => "Indonesia ", "desc" => "mobile", "name_ru" => "Индонезия ", "desc_ru" => "мобильные"],
    ["mask" => "+353(###)###-###", "cc" => "IE", "name" => "Ireland", "desc" => "", "name_ru" => "Ирландия", "desc_ru" => ""],
    ["mask" => "+972-5#-###-####", "cc" => "IL", "name" => "Israel ", "desc" => "mobile", "name_ru" => "Израиль ", "desc_ru" => "мобильные"],
    ["mask" => "+972-#-###-####", "cc" => "IL", "name" => "Israel", "desc" => "", "name_ru" => "Израиль", "desc_ru" => ""],
    ["mask" => "+91(####)###-###", "cc" => "IN", "name" => "India", "desc" => "", "name_ru" => "Индия", "desc_ru" => ""],
    ["mask" => "+246-###-####", "cc" => "IO", "name" => "Diego Garcia", "desc" => "", "name_ru" => "Диего-Гарсия", "desc_ru" => ""],
    ["mask" => "+964(###)###-####", "cc" => "IQ", "name" => "Iraq", "desc" => "", "name_ru" => "Ирак", "desc_ru" => ""],
    ["mask" => "+98(###)###-####", "cc" => "IR", "name" => "Iran", "desc" => "", "name_ru" => "Иран", "desc_ru" => ""],
    ["mask" => "+354-###-####", "cc" => "IS", "name" => "Iceland", "desc" => "", "name_ru" => "Исландия", "desc_ru" => ""],
    ["mask" => "+39(###)####-###", "cc" => "IT", "name" => "Italy", "desc" => "", "name_ru" => "Италия", "desc_ru" => ""],
    ["mask" => "+1(876)###-####", "cc" => "JM", "name" => "Jamaica", "desc" => "", "name_ru" => "Ямайка", "desc_ru" => ""],
    ["mask" => "+962-#-####-####", "cc" => "JO", "name" => "Jordan", "desc" => "", "name_ru" => "Иордания", "desc_ru" => ""],
    ["mask" => "+81-##-####-####", "cc" => "JP", "name" => "Japan ", "desc" => "mobile", "name_ru" => "Япония ", "desc_ru" => "мобильные"],
    ["mask" => "+81(###)###-###", "cc" => "JP", "name" => "Japan", "desc" => "", "name_ru" => "Япония", "desc_ru" => ""],
    ["mask" => "+254-###-######", "cc" => "KE", "name" => "Kenya", "desc" => "", "name_ru" => "Кения", "desc_ru" => ""],
    ["mask" => "+996(###)###-###", "cc" => "KG", "name" => "Kyrgyzstan", "desc" => "", "name_ru" => "Киргизия", "desc_ru" => ""],
    ["mask" => "+855-##-###-###", "cc" => "KH", "name" => "Cambodia", "desc" => "", "name_ru" => "Камбоджа", "desc_ru" => ""],
    ["mask" => "+686-##-###", "cc" => "KI", "name" => "Kiribati", "desc" => "", "name_ru" => "Кирибати", "desc_ru" => ""],
    ["mask" => "+269-##-#####", "cc" => "KM", "name" => "Comoros", "desc" => "", "name_ru" => "Коморы", "desc_ru" => ""],
    ["mask" => "+1(869)###-####", "cc" => "KN", "name" => "Saint Kitts & Nevis", "desc" => "", "name_ru" => "Сент-Китс и Невис", "desc_ru" => ""],
    ["mask" => "+850-191-###-####", "cc" => "KP", "name" => "DPR Korea (North) ", "desc" => "mobile", "name_ru" => "Корейская НДР ", "desc_ru" => "мобильные"],
    ["mask" => "+850-##-###-###", "cc" => "KP", "name" => "DPR Korea (North)", "desc" => "", "name_ru" => "Корейская НДР", "desc_ru" => ""],
    ["mask" => "+850-###-####-###", "cc" => "KP", "name" => "DPR Korea (North)", "desc" => "", "name_ru" => "Корейская НДР", "desc_ru" => ""],
    ["mask" => "+850-###-###", "cc" => "KP", "name" => "DPR Korea (North)", "desc" => "", "name_ru" => "Корейская НДР", "desc_ru" => ""],
    ["mask" => "+850-####-####", "cc" => "KP", "name" => "DPR Korea (North)", "desc" => "", "name_ru" => "Корейская НДР", "desc_ru" => ""],
    ["mask" => "+850-####-#############", "cc" => "KP", "name" => "DPR Korea (North)", "desc" => "", "name_ru" => "Корейская НДР", "desc_ru" => ""],
    ["mask" => "+82-##-###-####", "cc" => "KR", "name" => "Korea (South)", "desc" => "", "name_ru" => "Респ. Корея", "desc_ru" => ""],
    ["mask" => "+965-####-####", "cc" => "KW", "name" => "Kuwait", "desc" => "", "name_ru" => "Кувейт", "desc_ru" => ""],
    ["mask" => "+1(345)###-####", "cc" => "KY", "name" => "Cayman Islands", "desc" => "", "name_ru" => "Каймановы острова", "desc_ru" => ""],
    ["mask" => "+7(6##)###-##-##", "cc" => "KZ", "name" => "Kazakhstan", "desc" => "", "name_ru" => "Казахстан", "desc_ru" => ""],
    ["mask" => "+7(7##)###-##-##", "cc" => "KZ", "name" => "Kazakhstan", "desc" => "", "name_ru" => "Казахстан", "desc_ru" => ""],
    ["mask" => "+856(20##)###-###", "cc" => "LA", "name" => "Laos ", "desc" => "mobile", "name_ru" => "Лаос ", "desc_ru" => "мобильные"],
    ["mask" => "+856-##-###-###", "cc" => "LA", "name" => "Laos", "desc" => "", "name_ru" => "Лаос", "desc_ru" => ""],
    ["mask" => "+961-##-###-###", "cc" => "LB", "name" => "Lebanon ", "desc" => "mobile", "name_ru" => "Ливан ", "desc_ru" => "мобильные"],
    ["mask" => "+961-#-###-###", "cc" => "LB", "name" => "Lebanon", "desc" => "", "name_ru" => "Ливан", "desc_ru" => ""],
    ["mask" => "+1(758)###-####", "cc" => "LC", "name" => "Saint Lucia", "desc" => "", "name_ru" => "Сент-Люсия", "desc_ru" => ""],
    ["mask" => "+423(###)###-####", "cc" => "LI", "name" => "Liechtenstein", "desc" => "", "name_ru" => "Лихтенштейн", "desc_ru" => ""],
    ["mask" => "+94-##-###-####", "cc" => "LK", "name" => "Sri Lanka", "desc" => "", "name_ru" => "Шри-Ланка", "desc_ru" => ""],
    ["mask" => "+231-##-###-###", "cc" => "LR", "name" => "Liberia", "desc" => "", "name_ru" => "Либерия", "desc_ru" => ""],
    ["mask" => "+266-#-###-####", "cc" => "LS", "name" => "Lesotho", "desc" => "", "name_ru" => "Лесото", "desc_ru" => ""],
    ["mask" => "+370(###)##-###", "cc" => "LT", "name" => "Lithuania", "desc" => "", "name_ru" => "Литва", "desc_ru" => ""],
    ["mask" => "+352(###)###-###", "cc" => "LU", "name" => "Luxembourg", "desc" => "", "name_ru" => "Люксембург", "desc_ru" => ""],
    ["mask" => "+371-##-###-###", "cc" => "LV", "name" => "Latvia", "desc" => "", "name_ru" => "Латвия", "desc_ru" => ""],
    ["mask" => "+218-##-###-###", "cc" => "LY", "name" => "Libya", "desc" => "", "name_ru" => "Ливия", "desc_ru" => ""],
    ["mask" => "+218-21-###-####", "cc" => "LY", "name" => "Libya", "desc" => "Tripoli", "name_ru" => "Ливия", "desc_ru" => "Триполи"],
    ["mask" => "+212-##-####-###", "cc" => "MA", "name" => "Morocco", "desc" => "", "name_ru" => "Марокко", "desc_ru" => ""],
    ["mask" => "+377(###)###-###", "cc" => "MC", "name" => "Monaco", "desc" => "", "name_ru" => "Монако", "desc_ru" => ""],
    ["mask" => "+377-##-###-###", "cc" => "MC", "name" => "Monaco", "desc" => "", "name_ru" => "Монако", "desc_ru" => ""],
    ["mask" => "+373-####-####", "cc" => "MD", "name" => "Moldova", "desc" => "", "name_ru" => "Молдова", "desc_ru" => ""],
    ["mask" => "+382-##-###-###", "cc" => "ME", "name" => "Montenegro", "desc" => "", "name_ru" => "Черногория", "desc_ru" => ""],
    ["mask" => "+261-##-##-#####", "cc" => "MG", "name" => "Madagascar", "desc" => "", "name_ru" => "Мадагаскар", "desc_ru" => ""],
    ["mask" => "+692-###-####", "cc" => "MH", "name" => "Marshall Islands", "desc" => "", "name_ru" => "Маршалловы Острова", "desc_ru" => ""],
    ["mask" => "+389-##-###-###", "cc" => "MK", "name" => "Republic of Macedonia", "desc" => "", "name_ru" => "Респ. Македония", "desc_ru" => ""],
    ["mask" => "+223-##-##-####", "cc" => "ML", "name" => "Mali", "desc" => "", "name_ru" => "Мали", "desc_ru" => ""],
    ["mask" => "+95-##-###-###", "cc" => "MM", "name" => "Burma (Myanmar)", "desc" => "", "name_ru" => "Бирма (Мьянма)", "desc_ru" => ""],
    ["mask" => "+95-#-###-###", "cc" => "MM", "name" => "Burma (Myanmar)", "desc" => "", "name_ru" => "Бирма (Мьянма)", "desc_ru" => ""],
    ["mask" => "+95-###-###", "cc" => "MM", "name" => "Burma (Myanmar)", "desc" => "", "name_ru" => "Бирма (Мьянма)", "desc_ru" => ""],
    ["mask" => "+976-##-##-####", "cc" => "MN", "name" => "Mongolia", "desc" => "", "name_ru" => "Монголия", "desc_ru" => ""],
    ["mask" => "+853-####-####", "cc" => "MO", "name" => "Macau", "desc" => "", "name_ru" => "Макао", "desc_ru" => ""],
    ["mask" => "+1(670)###-####", "cc" => "MP", "name" => "Northern Mariana Islands", "desc" => "", "name_ru" => "Северные Марианские острова Сайпан", "desc_ru" => ""],
    ["mask" => "+596(###)##-##-##", "cc" => "MQ", "name" => "Martinique", "desc" => "", "name_ru" => "Мартиника", "desc_ru" => ""],
    ["mask" => "+222-##-##-####", "cc" => "MR", "name" => "Mauritania", "desc" => "", "name_ru" => "Мавритания", "desc_ru" => ""],
    ["mask" => "+1(664)###-####", "cc" => "MS", "name" => "Montserrat", "desc" => "", "name_ru" => "Монтсеррат", "desc_ru" => ""],
    ["mask" => "+356-####-####", "cc" => "MT", "name" => "Malta", "desc" => "", "name_ru" => "Мальта", "desc_ru" => ""],
    ["mask" => "+230-###-####", "cc" => "MU", "name" => "Mauritius", "desc" => "", "name_ru" => "Маврикий", "desc_ru" => ""],
    ["mask" => "+960-###-####", "cc" => "MV", "name" => "Maldives", "desc" => "", "name_ru" => "Мальдивские острова", "desc_ru" => ""],
    ["mask" => "+265-1-###-###", "cc" => "MW", "name" => "Malawi", "desc" => "Telecom Ltd", "name_ru" => "Малави", "desc_ru" => "Telecom Ltd"],
    ["mask" => "+265-#-####-####", "cc" => "MW", "name" => "Malawi", "desc" => "", "name_ru" => "Малави", "desc_ru" => ""],
    ["mask" => "+52(###)###-####", "cc" => "MX", "name" => "Mexico", "desc" => "", "name_ru" => "Мексика", "desc_ru" => ""],
    ["mask" => "+52-##-##-####", "cc" => "MX", "name" => "Mexico", "desc" => "", "name_ru" => "Мексика", "desc_ru" => ""],
    ["mask" => "+60-##-###-####", "cc" => "MY", "name" => "Malaysia ", "desc" => "mobile", "name_ru" => "Малайзия ", "desc_ru" => "мобильные"],
    ["mask" => "+60(###)###-###", "cc" => "MY", "name" => "Malaysia", "desc" => "", "name_ru" => "Малайзия", "desc_ru" => ""],
    ["mask" => "+60-##-###-###", "cc" => "MY", "name" => "Malaysia", "desc" => "", "name_ru" => "Малайзия", "desc_ru" => ""],
    ["mask" => "+60-#-###-###", "cc" => "MY", "name" => "Malaysia", "desc" => "", "name_ru" => "Малайзия", "desc_ru" => ""],
    ["mask" => "+258-##-###-###", "cc" => "MZ", "name" => "Mozambique", "desc" => "", "name_ru" => "Мозамбик", "desc_ru" => ""],
    ["mask" => "+264-##-###-####", "cc" => "NA", "name" => "Namibia", "desc" => "", "name_ru" => "Намибия", "desc_ru" => ""],
    ["mask" => "+687-##-####", "cc" => "NC", "name" => "New Caledonia", "desc" => "", "name_ru" => "Новая Каледония", "desc_ru" => ""],
    ["mask" => "+227-##-##-####", "cc" => "NE", "name" => "Niger", "desc" => "", "name_ru" => "Нигер", "desc_ru" => ""],
    ["mask" => "+672-3##-###", "cc" => "NF", "name" => "Norfolk Island", "desc" => "", "name_ru" => "Норфолк (остров)", "desc_ru" => ""],
    ["mask" => "+234(###)###-####", "cc" => "NG", "name" => "Nigeria", "desc" => "", "name_ru" => "Нигерия", "desc_ru" => ""],
    ["mask" => "+234-##-###-###", "cc" => "NG", "name" => "Nigeria", "desc" => "", "name_ru" => "Нигерия", "desc_ru" => ""],
    ["mask" => "+234-##-###-##", "cc" => "NG", "name" => "Nigeria", "desc" => "", "name_ru" => "Нигерия", "desc_ru" => ""],
    ["mask" => "+234(###)###-####", "cc" => "NG", "name" => "Nigeria ", "desc" => "mobile", "name_ru" => "Нигерия ", "desc_ru" => "мобильные"],
    ["mask" => "+505-####-####", "cc" => "NI", "name" => "Nicaragua", "desc" => "", "name_ru" => "Никарагуа", "desc_ru" => ""],
    ["mask" => "+31-##-###-####", "cc" => "NL", "name" => "Netherlands", "desc" => "", "name_ru" => "Нидерланды", "desc_ru" => ""],
    ["mask" => "+47(###)##-###", "cc" => "NO", "name" => "Norway", "desc" => "", "name_ru" => "Норвегия", "desc_ru" => ""],
    ["mask" => "+977-##-###-###", "cc" => "NP", "name" => "Nepal", "desc" => "", "name_ru" => "Непал", "desc_ru" => ""],
    ["mask" => "+674-###-####", "cc" => "NR", "name" => "Nauru", "desc" => "", "name_ru" => "Науру", "desc_ru" => ""],
    ["mask" => "+683-####", "cc" => "NU", "name" => "Niue", "desc" => "", "name_ru" => "Ниуэ", "desc_ru" => ""],
    ["mask" => "+64(###)###-###", "cc" => "NZ", "name" => "New Zealand", "desc" => "", "name_ru" => "Новая Зеландия", "desc_ru" => ""],
    ["mask" => "+64-##-###-###", "cc" => "NZ", "name" => "New Zealand", "desc" => "", "name_ru" => "Новая Зеландия", "desc_ru" => ""],
    ["mask" => "+64(###)###-####", "cc" => "NZ", "name" => "New Zealand", "desc" => "", "name_ru" => "Новая Зеландия", "desc_ru" => ""],
    ["mask" => "+968-##-###-###", "cc" => "OM", "name" => "Oman", "desc" => "", "name_ru" => "Оман", "desc_ru" => ""],
    ["mask" => "+507-###-####", "cc" => "PA", "name" => "Panama", "desc" => "", "name_ru" => "Панама", "desc_ru" => ""],
    ["mask" => "+51(###)###-###", "cc" => "PE", "name" => "Peru", "desc" => "", "name_ru" => "Перу", "desc_ru" => ""],
    ["mask" => "+689-##-##-##", "cc" => "PF", "name" => "French Polynesia", "desc" => "", "name_ru" => "Французская Полинезия (Таити)", "desc_ru" => ""],
    ["mask" => "+675(###)##-###", "cc" => "PG", "name" => "Papua New Guinea", "desc" => "", "name_ru" => "Папуа-Новая Гвинея", "desc_ru" => ""],
    ["mask" => "+63(###)###-####", "cc" => "PH", "name" => "Philippines", "desc" => "", "name_ru" => "Филиппины", "desc_ru" => ""],
    ["mask" => "+92(###)###-####", "cc" => "PK", "name" => "Pakistan", "desc" => "", "name_ru" => "Пакистан", "desc_ru" => ""],
    ["mask" => "+48(###)###-###", "cc" => "PL", "name" => "Poland", "desc" => "", "name_ru" => "Польша", "desc_ru" => ""],
    ["mask" => "+970-##-###-####", "cc" => "PS", "name" => "Palestine", "desc" => "", "name_ru" => "Палестина", "desc_ru" => ""],
    ["mask" => "+351-##-###-####", "cc" => "PT", "name" => "Portugal", "desc" => "", "name_ru" => "Португалия", "desc_ru" => ""],
    ["mask" => "+680-###-####", "cc" => "PW", "name" => "Palau", "desc" => "", "name_ru" => "Палау", "desc_ru" => ""],
    ["mask" => "+595(###)###-###", "cc" => "PY", "name" => "Paraguay", "desc" => "", "name_ru" => "Парагвай", "desc_ru" => ""],
    ["mask" => "+974-####-####", "cc" => "QA", "name" => "Qatar", "desc" => "", "name_ru" => "Катар", "desc_ru" => ""],
    ["mask" => "+262-#####-####", "cc" => "RE", "name" => "Reunion", "desc" => "", "name_ru" => "Реюньон", "desc_ru" => ""],
    ["mask" => "+40-##-###-####", "cc" => "RO", "name" => "Romania", "desc" => "", "name_ru" => "Румыния", "desc_ru" => ""],
    ["mask" => "+381-##-###-####", "cc" => "RS", "name" => "Serbia", "desc" => "", "name_ru" => "Сербия", "desc_ru" => ""],
    ["mask" => "+7(###)###-##-##", "cc" => "RU", "name" => "Russia", "desc" => "", "name_ru" => "Россия", "desc_ru" => ""],
    ["mask" => "+250(###)###-###", "cc" => "RW", "name" => "Rwanda", "desc" => "", "name_ru" => "Руанда", "desc_ru" => ""],
    ["mask" => "+966-5-####-####", "cc" => "SA", "name" => "Saudi Arabia ", "desc" => "mobile", "name_ru" => "Саудовская Аравия ", "desc_ru" => "мобильные"],
    ["mask" => "+966-#-###-####", "cc" => "SA", "name" => "Saudi Arabia", "desc" => "", "name_ru" => "Саудовская Аравия", "desc_ru" => ""],
    ["mask" => "+677-###-####", "cc" => "SB", "name" => "Solomon Islands ", "desc" => "mobile", "name_ru" => "Соломоновы Острова ", "desc_ru" => "мобильные"],
    ["mask" => "+677-#####", "cc" => "SB", "name" => "Solomon Islands", "desc" => "", "name_ru" => "Соломоновы Острова", "desc_ru" => ""],
    ["mask" => "+248-#-###-###", "cc" => "SC", "name" => "Seychelles", "desc" => "", "name_ru" => "Сейшелы", "desc_ru" => ""],
    ["mask" => "+249-##-###-####", "cc" => "SD", "name" => "Sudan", "desc" => "", "name_ru" => "Судан", "desc_ru" => ""],
    ["mask" => "+46-##-###-####", "cc" => "SE", "name" => "Sweden", "desc" => "", "name_ru" => "Швеция", "desc_ru" => ""],
    ["mask" => "+65-####-####", "cc" => "SG", "name" => "Singapore", "desc" => "", "name_ru" => "Сингапур", "desc_ru" => ""],
    ["mask" => "+290-####", "cc" => "SH", "name" => "Saint Helena", "desc" => "", "name_ru" => "Остров Святой Елены", "desc_ru" => ""],
    ["mask" => "+290-####", "cc" => "SH", "name" => "Tristan da Cunha", "desc" => "", "name_ru" => "Тристан-да-Кунья", "desc_ru" => ""],
    ["mask" => "+386-##-###-###", "cc" => "SI", "name" => "Slovenia", "desc" => "", "name_ru" => "Словения", "desc_ru" => ""],
    ["mask" => "+421(###)###-###", "cc" => "SK", "name" => "Slovakia", "desc" => "", "name_ru" => "Словакия", "desc_ru" => ""],
    ["mask" => "+232-##-######", "cc" => "SL", "name" => "Sierra Leone", "desc" => "", "name_ru" => "Сьерра-Леоне", "desc_ru" => ""],
    ["mask" => "+378-####-######", "cc" => "SM", "name" => "San Marino", "desc" => "", "name_ru" => "Сан-Марино", "desc_ru" => ""],
    ["mask" => "+221-##-###-####", "cc" => "SN", "name" => "Senegal", "desc" => "", "name_ru" => "Сенегал", "desc_ru" => ""],
    ["mask" => "+252-##-###-###", "cc" => "SO", "name" => "Somalia", "desc" => "", "name_ru" => "Сомали", "desc_ru" => ""],
    ["mask" => "+252-#-###-###", "cc" => "SO", "name" => "Somalia", "desc" => "", "name_ru" => "Сомали", "desc_ru" => ""],
    ["mask" => "+252-#-###-###", "cc" => "SO", "name" => "Somalia ", "desc" => "mobile", "name_ru" => "Сомали ", "desc_ru" => "мобильные"],
    ["mask" => "+597-###-####", "cc" => "SR", "name" => "Suriname ", "desc" => "mobile", "name_ru" => "Суринам ", "desc_ru" => "мобильные"],
    ["mask" => "+597-###-###", "cc" => "SR", "name" => "Suriname", "desc" => "", "name_ru" => "Суринам", "desc_ru" => ""],
    ["mask" => "+211-##-###-####", "cc" => "SS", "name" => "South Sudan", "desc" => "", "name_ru" => "Южный Судан", "desc_ru" => ""],
    ["mask" => "+239-##-#####", "cc" => "ST", "name" => "Sao Tome and Principe", "desc" => "", "name_ru" => "Сан-Томе и Принсипи", "desc_ru" => ""],
    ["mask" => "+503-##-##-####", "cc" => "SV", "name" => "El Salvador", "desc" => "", "name_ru" => "Сальвадор", "desc_ru" => ""],
    ["mask" => "+1(721)###-####", "cc" => "SX", "name" => "Sint Maarten", "desc" => "", "name_ru" => "Синт-Маартен", "desc_ru" => ""],
    ["mask" => "+963-##-####-###", "cc" => "SY", "name" => "Syrian Arab Republic", "desc" => "", "name_ru" => "Сирийская арабская республика", "desc_ru" => ""],
    ["mask" => "+268-##-##-####", "cc" => "SZ", "name" => "Swaziland", "desc" => "", "name_ru" => "Свазиленд", "desc_ru" => ""],
    ["mask" => "+1(649)###-####", "cc" => "TC", "name" => "Turks & Caicos", "desc" => "", "name_ru" => "Тёркс и Кайкос", "desc_ru" => ""],
    ["mask" => "+235-##-##-##-##", "cc" => "TD", "name" => "Chad", "desc" => "", "name_ru" => "Чад", "desc_ru" => ""],
    ["mask" => "+228-##-###-###", "cc" => "TG", "name" => "Togo", "desc" => "", "name_ru" => "Того", "desc_ru" => ""],
    ["mask" => "+66-##-###-####", "cc" => "TH", "name" => "Thailand ", "desc" => "mobile", "name_ru" => "Таиланд ", "desc_ru" => "мобильные"],
    ["mask" => "+66-##-###-###", "cc" => "TH", "name" => "Thailand", "desc" => "", "name_ru" => "Таиланд", "desc_ru" => ""],
    ["mask" => "+992-##-###-####", "cc" => "TJ", "name" => "Tajikistan", "desc" => "", "name_ru" => "Таджикистан", "desc_ru" => ""],
    ["mask" => "+690-####", "cc" => "TK", "name" => "Tokelau", "desc" => "", "name_ru" => "Токелау", "desc_ru" => ""],
    ["mask" => "+670-###-####", "cc" => "TL", "name" => "East Timor", "desc" => "", "name_ru" => "Восточный Тимор", "desc_ru" => ""],
    ["mask" => "+670-77#-#####", "cc" => "TL", "name" => "East Timor", "desc" => "Timor Telecom", "name_ru" => "Восточный Тимор", "desc_ru" => "Timor Telecom"],
    ["mask" => "+670-78#-#####", "cc" => "TL", "name" => "East Timor", "desc" => "Timor Telecom", "name_ru" => "Восточный Тимор", "desc_ru" => "Timor Telecom"],
    ["mask" => "+993-#-###-####", "cc" => "TM", "name" => "Turkmenistan", "desc" => "", "name_ru" => "Туркменистан", "desc_ru" => ""],
    ["mask" => "+216-##-###-###", "cc" => "TN", "name" => "Tunisia", "desc" => "", "name_ru" => "Тунис", "desc_ru" => ""],
    ["mask" => "+676-#####", "cc" => "TO", "name" => "Tonga", "desc" => "", "name_ru" => "Тонга", "desc_ru" => ""],
    ["mask" => "+90(###)###-####", "cc" => "TR", "name" => "Turkey", "desc" => "", "name_ru" => "Турция", "desc_ru" => ""],
    ["mask" => "+1(868)###-####", "cc" => "TT", "name" => "Trinidad & Tobago", "desc" => "", "name_ru" => "Тринидад и Тобаго", "desc_ru" => ""],
    ["mask" => "+688-90####", "cc" => "TV", "name" => "Tuvalu ", "desc" => "mobile", "name_ru" => "Тувалу ", "desc_ru" => "мобильные"],
    ["mask" => "+688-2####", "cc" => "TV", "name" => "Tuvalu", "desc" => "", "name_ru" => "Тувалу", "desc_ru" => ""],
    ["mask" => "+886-#-####-####", "cc" => "TW", "name" => "Taiwan", "desc" => "", "name_ru" => "Тайвань", "desc_ru" => ""],
    ["mask" => "+886-####-####", "cc" => "TW", "name" => "Taiwan", "desc" => "", "name_ru" => "Тайвань", "desc_ru" => ""],
    ["mask" => "+255-##-###-####", "cc" => "TZ", "name" => "Tanzania", "desc" => "", "name_ru" => "Танзания", "desc_ru" => ""],
    ["mask" => "+380(##)###-##-##", "cc" => "UA", "name" => "Ukraine", "desc" => "", "name_ru" => "Украина", "desc_ru" => ""],
    ["mask" => "+256(###)###-###", "cc" => "UG", "name" => "Uganda", "desc" => "", "name_ru" => "Уганда", "desc_ru" => ""],
    ["mask" => "+44-##-####-####", "cc" => "UK", "name" => "United Kingdom", "desc" => "", "name_ru" => "Великобритания", "desc_ru" => ""],
    ["mask" => "+598-#-###-##-##", "cc" => "UY", "name" => "Uruguay", "desc" => "", "name_ru" => "Уругвай", "desc_ru" => ""],
    ["mask" => "+998-##-###-####", "cc" => "UZ", "name" => "Uzbekistan", "desc" => "", "name_ru" => "Узбекистан", "desc_ru" => ""],
    ["mask" => "+39-6-698-#####", "cc" => "VA", "name" => "Vatican City", "desc" => "", "name_ru" => "Ватикан", "desc_ru" => ""],
    ["mask" => "+1(784)###-####", "cc" => "VC", "name" => "Saint Vincent & the Grenadines", "desc" => "", "name_ru" => "Сент-Винсент и Гренадины", "desc_ru" => ""],
    ["mask" => "+58(###)###-####", "cc" => "VE", "name" => "Venezuela", "desc" => "", "name_ru" => "Венесуэла", "desc_ru" => ""],
    ["mask" => "+1(284)###-####", "cc" => "VG", "name" => "British Virgin Islands", "desc" => "", "name_ru" => "Британские Виргинские острова", "desc_ru" => ""],
    ["mask" => "+1(340)###-####", "cc" => "VI", "name" => "US Virgin Islands", "desc" => "", "name_ru" => "Американские Виргинские острова", "desc_ru" => ""],
    ["mask" => "+84-##-####-###", "cc" => "VN", "name" => "Vietnam", "desc" => "", "name_ru" => "Вьетнам", "desc_ru" => ""],
    ["mask" => "+84(###)####-###", "cc" => "VN", "name" => "Vietnam", "desc" => "", "name_ru" => "Вьетнам", "desc_ru" => ""],
    ["mask" => "+678-##-#####", "cc" => "VU", "name" => "Vanuatu ", "desc" => "mobile", "name_ru" => "Вануату ", "desc_ru" => "мобильные"],
    ["mask" => "+678-#####", "cc" => "VU", "name" => "Vanuatu", "desc" => "", "name_ru" => "Вануату", "desc_ru" => ""],
    ["mask" => "+681-##-####", "cc" => "WF", "name" => "Wallis and Futuna", "desc" => "", "name_ru" => "Уоллис и Футуна", "desc_ru" => ""],
    ["mask" => "+685-##-####", "cc" => "WS", "name" => "Samoa", "desc" => "", "name_ru" => "Самоа", "desc_ru" => ""],
    ["mask" => "+967-###-###-###", "cc" => "YE", "name" => "Yemen ", "desc" => "mobile", "name_ru" => "Йемен ", "desc_ru" => "мобильные"],
    ["mask" => "+967-#-###-###", "cc" => "YE", "name" => "Yemen", "desc" => "", "name_ru" => "Йемен", "desc_ru" => ""],
    ["mask" => "+967-##-###-###", "cc" => "YE", "name" => "Yemen", "desc" => "", "name_ru" => "Йемен", "desc_ru" => ""],
    ["mask" => "+27-##-###-####", "cc" => "ZA", "name" => "South Africa", "desc" => "", "name_ru" => "Южно-Африканская Респ.", "desc_ru" => ""],
    ["mask" => "+260-##-###-####", "cc" => "ZM", "name" => "Zambia", "desc" => "", "name_ru" => "Замбия", "desc_ru" => ""],
    ["mask" => "+263-#-######", "cc" => "ZW", "name" => "Zimbabwe", "desc" => "", "name_ru" => "Зимбабве", "desc_ru" => ""],
    ["mask" => "+1(###)###-####", "cc" => "US", "name" => "USA", "desc" => "", "name_ru" => "США", "desc_ru" => ""],
    ["mask" => "+1(###)###-####", "cc" => "CA", "name" => "Canada", "desc" => "", "name_ru" => "Канада", "desc_ru" => ""]
]

regions.each do |region|
  Region.create(region)
end
